from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


PROMPT_DIR = Path("firstresearch/prompts")
CONFIGS = [
    Path("configs/deepseek_strong_baselines.yaml"),
    Path("configs/deepseek_strong_baselines_gemini_judge.yaml"),
    Path("configs/deepseek_benchmark.yaml"),
    Path("configs/deepseek_ablation.yaml"),
    Path("configs/deepseek_ablation_repeated.yaml"),
    Path("configs/deepseek_ablation_repeated_crossjudge.yaml"),
    Path("configs/deepseek_ablation_repeated_gemini_judge.yaml"),
    Path("configs/deepseek_combo_study.yaml"),
    Path("configs/deepseek_stress_generalization.yaml"),
]


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a reproducibility appendix from local prompts and configs.")
    parser.add_argument("--output", default="papers/reproducibility_appendix.md")
    args = parser.parse_args()

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_appendix(), encoding="utf-8")
    print(output)


def render_appendix() -> str:
    lines = [
        "# Reproducibility Appendix",
        "",
        "This appendix is generated from repository files so that prompt and configuration details stay synchronized with the implementation.",
        "",
        "## Commands",
        "",
        "Full paper evidence workflow:",
        "",
        "```bash",
        "python scripts/run_paper_evidence_pipeline.py",
        "```",
        "",
        "Use `--skip-credentialed` to regenerate non-API artifacts such as the appendix, manifest, audit, and any human-review packets whose inputs already exist.",
        "",
        "Strong-baseline evaluation:",
        "",
        "```bash",
        "python scripts/run_benchmark.py --config configs/deepseek_strong_baselines.yaml",
        "python scripts/audit_package_artifacts.py \\",
        "  --results outputs/reports/deepseek_strong_baselines_10topics.csv \\",
        "  --output outputs/reports/deepseek_strong_baselines_package_audit.md \\",
        "  --json-output outputs/reports/deepseek_strong_baselines_package_audit.json \\",
        "  --strict",
        "python scripts/audit_results_table.py \\",
        "  --results outputs/reports/deepseek_strong_baselines_10topics.csv \\",
        "  --manuscript papers/firstresearch_draft.md \\",
        "  --output outputs/reports/results_table_audit.md \\",
        "  --json-output outputs/reports/results_table_audit.json \\",
        "  --strict",
        "python scripts/generate_baseline_fidelity_report.py \\",
        "  --config configs/deepseek_strong_baselines.yaml \\",
        "  --output outputs/reports/baseline_fidelity_report.md \\",
        "  --json-output outputs/reports/baseline_fidelity_report.json",
        "python scripts/rescore_packages.py --config configs/deepseek_strong_baselines_gemini_judge.yaml",
        "python scripts/generate_report.py \\",
        "  --results outputs/reports/deepseek_strong_baselines_gemini_judge_results.csv \\",
        "  --output outputs/reports/deepseek_strong_baselines_gemini_judge_report.md \\",
        "  --table-output outputs/reports/deepseek_strong_baselines_gemini_judge_table.csv",
        "python scripts/analyze_judge_agreement.py \\",
        "  --primary-results outputs/reports/deepseek_strong_baselines_10topics.csv \\",
        "  --secondary-results outputs/reports/deepseek_strong_baselines_gemini_judge_results.csv \\",
        "  --output outputs/reports/deepseek_strong_baselines_gemini_judge_agreement.md \\",
        "  --table-output outputs/reports/deepseek_strong_baselines_gemini_judge_agreement.csv",
        "python scripts/audit_references.py \\",
        "  --registry papers/reference_registry.yaml \\",
        "  --manuscript papers/firstresearch_draft.md \\",
        "  --output outputs/reports/reference_audit.md \\",
        "  --json-output outputs/reports/reference_audit.json \\",
        "  --strict",
        "```",
        "",
        "Repeated ablation evaluation:",
        "",
        "```bash",
        "python scripts/run_benchmark.py --config configs/deepseek_ablation_repeated.yaml --resume --target-rows 70",
        "python scripts/generate_report.py \\",
        "  --results outputs/reports/deepseek_ablation_repeated_results.csv \\",
        "  --output outputs/reports/deepseek_ablation_repeated_report.md \\",
        "  --table-output outputs/reports/deepseek_ablation_repeated_table.csv",
        "python scripts/analyze_repeated_results.py \\",
        "  --results outputs/reports/deepseek_ablation_repeated_results.csv \\",
        "  --output outputs/reports/deepseek_ablation_repeated_stability.md \\",
        "  --table-output outputs/reports/deepseek_ablation_repeated_stability.csv \\",
        "  --reference-system firstresearch",
        "# Continue to the full three-replicate study by omitting --target-rows 70.",
        "```",
        "",
        "Cross-domain stress benchmark:",
        "",
        "```bash",
        "python scripts/run_benchmark.py --config configs/deepseek_stress_generalization.yaml",
        "python scripts/generate_report.py \\",
        "  --results outputs/reports/deepseek_stress_generalization_results.csv \\",
        "  --output outputs/reports/deepseek_stress_generalization_report.md \\",
        "  --table-output outputs/reports/deepseek_stress_generalization_table.csv",
        "```",
        "",
        "Combination study with co-scientist-style question debate refinement:",
        "",
        "```bash",
        "python scripts/run_benchmark.py --config configs/deepseek_combo_study.yaml --resume",
        "python scripts/generate_report.py \\",
        "  --results outputs/reports/deepseek_combo_study_results.csv \\",
        "  --output outputs/reports/deepseek_combo_study_report.md \\",
        "  --table-output outputs/reports/deepseek_combo_study_table.csv",
        "```",
        "",
        "Independent-judge rescore of generated ablation packages:",
        "",
        "```bash",
        "export OPENAI_COMPAT_API_KEY=\"your-judge-key\"",
        "export OPENAI_COMPAT_BASE_URL=\"https://your-openai-compatible-endpoint\"",
        "export OPENAI_COMPAT_MODEL=\"your-judge-model\"",
        "python scripts/rescore_packages.py --config configs/deepseek_ablation_repeated_crossjudge.yaml",
        "# Or use Gemini directly as the independent judge:",
        "# export GEMINI_API_KEY=\"your-gemini-key\"",
        "# python scripts/rescore_packages.py --config configs/deepseek_ablation_repeated_gemini_judge.yaml",
        "python scripts/generate_report.py \\",
        "  --results outputs/reports/deepseek_ablation_repeated_crossjudge_results.csv \\",
        "  --output outputs/reports/deepseek_ablation_repeated_crossjudge_report.md \\",
        "  --table-output outputs/reports/deepseek_ablation_repeated_crossjudge_table.csv",
        "python scripts/analyze_judge_agreement.py \\",
        "  --primary-results outputs/reports/deepseek_ablation_repeated_results.csv \\",
        "  --secondary-results outputs/reports/deepseek_ablation_repeated_crossjudge_results.csv \\",
        "  --output outputs/reports/deepseek_ablation_repeated_judge_agreement.md \\",
        "  --table-output outputs/reports/deepseek_ablation_repeated_judge_agreement.csv",
        "```",
        "",
        "Human review packet export:",
        "",
        "```bash",
        "python scripts/generate_human_review_protocol.py \\",
        "  --output outputs/reports/human_review_protocol.md \\",
        "  --json-output outputs/reports/human_review_protocol.json",
        "python scripts/export_human_review_packet.py \\",
        "  --results outputs/reports/deepseek_ablation_repeated_results.csv \\",
        "  --output-dir outputs/human_review/deepseek_ablation_repeated \\",
        "  --seed 13",
        "```",
        "",
        "Paper evidence audit:",
        "",
        "```bash",
        "python scripts/generate_artifact_manifest.py \\",
        "  --output outputs/reports/artifact_manifest.json \\",
        "  --markdown-output outputs/reports/artifact_manifest.md",
        "python scripts/audit_paper_evidence.py \\",
        "  --output outputs/reports/paper_evidence_audit.md \\",
        "  --json-output outputs/reports/paper_evidence_audit.json \\",
        "  --strict",
        "python scripts/audit_claim_evidence.py \\",
        "  --registry papers/claim_evidence_registry.yaml \\",
        "  --evidence-audit outputs/reports/paper_evidence_audit.json \\",
        "  --manuscript papers/firstresearch_draft.md \\",
        "  --output outputs/reports/claim_evidence_audit.md \\",
        "  --json-output outputs/reports/claim_evidence_audit.json \\",
        "  --strict",
        "python scripts/generate_submission_readiness_report.py \\",
        "  --evidence-audit outputs/reports/paper_evidence_audit.json \\",
        "  --claim-audit outputs/reports/claim_evidence_audit.json \\",
        "  --pipeline-status outputs/reports/paper_evidence_pipeline_status.json \\",
        "  --output outputs/reports/submission_readiness_report.md \\",
        "  --json-output outputs/reports/submission_readiness_report.json",
        "```",
        "",
        "Submission-readiness gate after repeated ablation, independent judge, and human-review evidence are complete:",
        "",
        "```bash",
        "python scripts/audit_paper_evidence.py \\",
        "  --output outputs/reports/paper_evidence_audit.md \\",
        "  --json-output outputs/reports/paper_evidence_audit.json \\",
        "  --strict \\",
        "  --require-optional",
        "```",
        "",
        "Scalar human review analysis after reviewers complete `human_scores.csv`:",
        "",
        "```bash",
        "python scripts/analyze_human_review.py \\",
        "  --assignments outputs/human_review/deepseek_ablation_repeated/assignments_private.json \\",
        "  --scores outputs/human_review/deepseek_ablation_repeated/human_scores.csv \\",
        "  --output outputs/human_review/deepseek_ablation_repeated/human_review_report.md \\",
        "  --table-output outputs/human_review/deepseek_ablation_repeated/human_review_summary.csv",
        "```",
        "",
        "Pairwise preference packet export:",
        "",
        "```bash",
        "python scripts/export_pairwise_review_packet.py \\",
        "  --results outputs/reports/deepseek_ablation_repeated_results.csv \\",
        "  --output-dir outputs/human_review/deepseek_ablation_repeated_pairwise \\",
        "  --reference-system firstresearch \\",
        "  --seed 17",
        "```",
        "",
        "Pairwise preference analysis after reviewers complete `pairwise_decisions.csv`:",
        "",
        "```bash",
        "python scripts/analyze_pairwise_review.py \\",
        "  --assignments outputs/human_review/deepseek_ablation_repeated_pairwise/pair_assignments_private.json \\",
        "  --decisions outputs/human_review/deepseek_ablation_repeated_pairwise/pairwise_decisions.csv \\",
        "  --output outputs/human_review/deepseek_ablation_repeated_pairwise/pairwise_report.md \\",
        "  --table-output outputs/human_review/deepseek_ablation_repeated_pairwise/pairwise_summary.csv",
        "```",
        "",
        "## Benchmark Topics",
        "",
        "Topics are loaded from `data/topics_eval.jsonl`.",
        "",
        "## Configurations",
        "",
    ]
    for path in CONFIGS:
        lines.extend(_file_block(path, "yaml"))

    lines.extend(["", "## Agent Prompts", ""])
    for path in sorted(PROMPT_DIR.glob("*.md")):
        lines.extend(_file_block(path, "markdown"))
    return "\n".join(lines) + "\n"


def _file_block(path: Path, language: str) -> list[str]:
    text = path.read_text(encoding="utf-8")
    return [
        f"### `{path.as_posix()}`",
        "",
        f"```{language}",
        text.rstrip(),
        "```",
        "",
    ]


if __name__ == "__main__":
    main()
